// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bankLIB.Data;

#nullable disable

namespace bankLIB.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260921142849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bankLIB.Entities.Accounts", b =>
                {
                    b.Property<int>("AccNo")
                        .HasColumnType("int");

                    b.Property<decimal>("AccBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AccHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LoanTermYears")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AccNo");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("bankLIB.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("AccNo")
                        .HasColumnType("int");

                    b.Property<int?>("AccountsAccNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("AccountsAccNo");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("bankLIB.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccNo")
                        .HasColumnType("int");

                    b.Property<int?>("AccountsAccNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfterTransaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountsAccNo");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("bankLIB.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleInitial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bankLIB.Entities.Admin", b =>
                {
                    b.HasBaseType("bankLIB.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("bankLIB.Entities.Customer", b =>
                {
                    b.HasBaseType("bankLIB.Entities.User");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("bankLIB.Entities.Accounts", b =>
                {
                    b.HasOne("bankLIB.Entities.Customer", null)
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerUserId");
                });

            modelBuilder.Entity("bankLIB.Entities.ServiceRequest", b =>
                {
                    b.HasOne("bankLIB.Entities.Accounts", null)
                        .WithMany("ServiceRequests")
                        .HasForeignKey("AccountsAccNo");
                });

            modelBuilder.Entity("bankLIB.Entities.Transaction", b =>
                {
                    b.HasOne("bankLIB.Entities.Accounts", null)
                        .WithMany("Transactions")
                        .HasForeignKey("AccountsAccNo");
                });

            modelBuilder.Entity("bankLIB.Entities.Accounts", b =>
                {
                    b.Navigation("ServiceRequests");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("bankLIB.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
